### ISSUE TITLE
Problematic "use Origin Headers"

### ISSUE THREAD

**Issue by LukasGrebe** [stape-io/file-proxy-client#1]
Thank you for the excellent work in this Template.

I've noticed problems with the "Use Origin Headers for Response" flag.

if set, depending on the source File URL and Container Hosting used, I may get a 502 Bad Gateway response.
I assume this might be due to headers such as "Transfer-Encoding", "Connection (keep-alive)" or other headers.

I'm not sure what other headers a set natively from a GTM server side container.

Any advice on debugging would be much appreciated.

**Comment by Bukashk0zzz** [comment]
Hi,

You can use https://tagmanager.google.com/gallery/#/owners/gtm-templates-simo-ahava/templates/response-headers
Set it using all headers that you think can cause errors. 
Then, delete headers individually and determine which header caused the issue.

**Comment by LukasGrebe** [comment]
Hi @Bukashk0zzz , thanks for the reply!
I've identified transfer-encoding to cause the 502 response. I've created https://github.com/stape-io/file-proxy-client/pull/3 in case this may be relevant for others.

**Comment by Bukashk0zzz** [comment]
Merged

**Comment by Bukashk0zzz** [comment]
Thanks for the fix.
